#+TITLE: Sample Deno Project with an Org README

This is a sample project for testing the rendering of Org
files for [[https://deno.land/x]].

* This is a basic heading

With some content.

** This is a nested heading

Also with some content.

* Inline markup

Org supports various inline markup, including: *bold*,
/italic/, _underline_, +strikethrough+, ~inline code~, and
=verbatim=.

Inline markup can be *mixed if _you_ do it +right+!*.

* Links

You can have full URL links with descriptions, such as: [[https://duckduckgo.com][DuckDuckGo!]]

You can link without a description: [[https://duckduckgo.com]].

Link to a heading in the same document with a description:
 [[Inline markup][should take you to 'Inline markup']].

Link to a heading in same document without a description:
[[Inline markup]].

Link to a file without description: [[./CHANGELOG.org]].

Link to a file with description: [[./CHANGELOG.org][link to the changelog]].

Link to a file using =file:=: [[file:./CHANGELOG.org]].

* Lists

** Unordered, flat

- you can have
- flat
- unordered
- lists

** Unordered, nested

- you can (1)
  - nest (1.1)
    - lists (1.1.1)
  - too (1.2)
- ! (2)

** Ordered

1. you can (1)
   1. order (1.1)
   2. lists (1.2)
2. if you want (2)

** Checkboxes

- [X] checkboxes
  - [X] let you
- [ ] do fancy
- [1/2] things
  - [X] like
  - [ ] count
  - [ ] completion

* Code

#+BEGIN_SRC typescript
  function typescriptFunction() {
      console.log("We'd be remiss without support for code blocks!");
  }
#+END_SRC

* More complex headings

** TODO Heading with TODO keyword
** DONE Heading with DONE keyword

** Heading with tags                                     :tag1:@another_tag:

** TODO Heading with tags and keywords                    :tag1:@another_tag:

** Heading with property drawer
:PROPERTIES:
:CREATED:  [2021-06-24 Thu 15:50]
:END:

** [#B] Heading with priority

** TODO [#A] Heading with everything                      :a_tag:another_tag:
:PROPERTIES:
:CREATED:  [2021-06-24 Thu 15:51]
:END:

* Timestamps

** Inactive

With time: [2021-06-24 Thu 15:51]

Without time: [2021-06-24]

Without time (2): [2021-06-24 Thu]

** Active

With time: <2021-06-24 Thu 15:51>

Without time: <2021-06-24>

Without time (2): <2021-06-24 Thu>

* Footnote references

You can reference numbered footnotes[fn:1].

Named footnotes[fn:named].

Anonymous footnotes[fn::Anonymous footnote]

Named, inline footnotes[fn:named-inline: Named inline footnote].

And named inline footnotes can be referenced again[fn:named-inline].


[fn:1] A numbered footnote.

[fn:named] A named footnote.
